# Generated by Django 4.2 on 2023-06-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_remove_answer_likes_remove_question_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
